Repository rapid7/insightconnect-plugins, pull requests merged in 2020-03, with the labels that each got.

#394 Dig: Example Input Reference
  dig/.CHECKSUM
  dig/bin/komand_dig
  dig/help.md
  dig/komand_dig/connection/connection.py
  dig/plugin.spec.yaml
  dig/setup.py
Labels: WIP

#395 DF-4019: Update Jenkins Plugin Connection Test
  jenkins/.CHECKSUM
  jenkins/bin/komand_jenkins
  jenkins/help.md
  jenkins/komand_jenkins/actions/build_info/action.py
  jenkins/komand_jenkins/actions/build_info/schema.py
  jenkins/komand_jenkins/actions/build_job/action.py
  jenkins/komand_jenkins/connection/connection.py
  jenkins/komand_jenkins/connection/schema.py
  jenkins/plugin.spec.yaml
  jenkins/setup.py
  jenkins/tests/build_info.json
  jenkins/tests/build_job.json
Labels: Needs Testing

#400 Bug fixes with create_ticket and update_ticket action
  zendesk/.CHECKSUM
  zendesk/bin/komand_zendesk
  zendesk/help.md
  zendesk/komand_zendesk/actions/create_ticket/schema.py
  zendesk/komand_zendesk/actions/update_ticket/action.py
  zendesk/komand_zendesk/actions/update_ticket/schema.py
  zendesk/komand_zendesk/connection/schema.py
  zendesk/plugin.spec.yaml
  zendesk/setup.py
Labels: Do Not Merge, WIP
