Repository rapid7/insightconnect-plugins, pull requests merged in 2021-07, with the labels that each got.

#957 [MC-407, MC-581, MC-568] - Cybereason - Create Remediate Items, Update Isolate Machine actions
  plugins/cybereason/.CHECKSUM
  plugins/cybereason/bin/icon_cybereason
  plugins/cybereason/help.md
  plugins/cybereason/icon_cybereason/actions/__init__.py
  plugins/cybereason/icon_cybereason/actions/isolate_machine/action.py
  plugins/cybereason/icon_cybereason/actions/isolate_machine/schema.py
  plugins/cybereason/icon_cybereason/actions/remediate_items/__init__.py
  plugins/cybereason/icon_cybereason/actions/remediate_items/action.py
  plugins/cybereason/icon_cybereason/actions/remediate_items/schema.py
  plugins/cybereason/icon_cybereason/util/api.py
  plugins/cybereason/plugin.spec.yaml
  plugins/cybereason/setup.py
  plugins/cybereason/unit_test/__init__.py
  plugins/cybereason/unit_test/payloads/isolate_machine.json.resp
  plugins/cybereason/unit_test/payloads/remediate_items.json.resp
  plugins/cybereason/unit_test/payloads/sensor_details.json.resp
  plugins/cybereason/unit_test/test_isolate_machine.py
  plugins/cybereason/unit_test/test_remediate_items.py
  plugins/cybereason/unit_test/util.py
Labels: Needs 2nd Reviewer

#962 [MC-340][MC-579] Add JSON to CSV String action to CSV plugin
  plugins/csv/.CHECKSUM
  plugins/csv/bin/komand_csv
  plugins/csv/help.md
  plugins/csv/komand_csv/actions/__init__.py
  plugins/csv/komand_csv/actions/json_to_csv/action.py
  plugins/csv/komand_csv/actions/json_to_csv_bytes/__init__.py
  plugins/csv/komand_csv/actions/json_to_csv_bytes/action.py
  plugins/csv/komand_csv/actions/json_to_csv_bytes/schema.py
  plugins/csv/komand_csv/actions/json_to_csv_string/__init__.py
  plugins/csv/komand_csv/actions/json_to_csv_string/action.py
  plugins/csv/komand_csv/actions/json_to_csv_string/schema.py
  plugins/csv/komand_csv/util/utils.py
  plugins/csv/plugin.spec.yaml
  plugins/csv/setup.py
  plugins/csv/unit_test/__init__.py
  plugins/csv/unit_test/test_json_to_csv_bytes.py
  plugins/csv/unit_test/test_json_to_csv_string.py
Labels: Ready to Merge

#969 [MC-607][MC-608][MC-609] Add docs_url in Palo Alto Firewall, Cisco ASA and Fortinet FortiGate plugins
  plugins/cisco_asa/.CHECKSUM
  plugins/cisco_asa/bin/icon_cisco_asa
  plugins/cisco_asa/help.md
  plugins/cisco_asa/plugin.spec.yaml
  plugins/cisco_asa/setup.py
  plugins/fortinet_fortigate/.CHECKSUM
  plugins/fortinet_fortigate/bin/icon_fortinet_fortigate
  plugins/fortinet_fortigate/help.md
  plugins/fortinet_fortigate/plugin.spec.yaml
  plugins/fortinet_fortigate/setup.py
  plugins/palo_alto_pan_os/.CHECKSUM
  plugins/palo_alto_pan_os/bin/komand_palo_alto_pan_os
  plugins/palo_alto_pan_os/help.md
  plugins/palo_alto_pan_os/plugin.spec.yaml
  plugins/palo_alto_pan_os/setup.py
Labels: Ready to Merge

#932 Improve pagination in Search action in URLScan plugin
  plugins/urlscan/.CHECKSUM
  plugins/urlscan/bin/komand_urlscan
  plugins/urlscan/help.md
  plugins/urlscan/komand_urlscan/actions/search/action.py
  plugins/urlscan/komand_urlscan/actions/search/schema.py
  plugins/urlscan/plugin.spec.yaml
  plugins/urlscan/setup.py
Labels: Ready to Merge

#939 SOAR-5481 xdr alerts trigger & SOAR-5438 get file quarantine status
  plugins/palo_alto_cortex_xdr/.CHECKSUM
  plugins/palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
  plugins/palo_alto_cortex_xdr/help.md
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/__init__.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/get_file_quarantine_status/__init__.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/get_file_quarantine_status/action.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/get_file_quarantine_status/schema.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/connection/connection.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/__init__.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_alerts/__init__.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_alerts/schema.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_alerts/trigger.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_incidents/schema.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_incidents/trigger.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/api.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/util.py
  plugins/palo_alto_cortex_xdr/plugin.spec.yaml
  plugins/palo_alto_cortex_xdr/setup.py
  plugins/palo_alto_cortex_xdr/unit_test/test_get_incidents.py
Labels: Needs 2nd Reviewer, Unresolved Comments

#963 [MC-597] Close SQL DB Connection After Usage
  plugins/sql/.CHECKSUM
  plugins/sql/bin/komand_sql
  plugins/sql/help.md
  plugins/sql/komand_sql/actions/query/action.py
  plugins/sql/komand_sql/connection/connection.py
  plugins/sql/plugin.spec.yaml
  plugins/sql/setup.py
  prospector.yaml
Labels: Ready to Merge

#976 [No Ticket] - String Operations - Replace
  plugins/string/.CHECKSUM
  plugins/string/Dockerfile
  plugins/string/bin/komand_string
  plugins/string/help.md
  plugins/string/komand_string/actions/__init__.py
  plugins/string/komand_string/actions/replace/__init__.py
  plugins/string/komand_string/actions/replace/action.py
  plugins/string/komand_string/actions/replace/schema.py
  plugins/string/plugin.spec.yaml
  plugins/string/setup.py
  plugins/string/unit_test/__init__.py
  plugins/string/unit_test/test_replace.py
Labels: Ready to Merge

#978 [SOAR-6366] Get logs url change
  plugins/rapid7_insightidr/.CHECKSUM
  plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
  plugins/rapid7_insightidr/help.md
  plugins/rapid7_insightidr/komand_rapid7_insightidr/util/endpoints.py
  plugins/rapid7_insightidr/plugin.spec.yaml
  plugins/rapid7_insightidr/setup.py
  plugins/rapid7_insightidr/unit_test/test_get_all_logs.py
Labels: Ready to Merge

#909 MC-450, MC-451 & MC-598 - Abnormal Security - New Actions - Get Cases & Get Case Details
  plugins/abnormal_security/.CHECKSUM
  plugins/abnormal_security/bin/icon_abnormal_security
  plugins/abnormal_security/help.md
  plugins/abnormal_security/icon_abnormal_security/actions/__init__.py
  plugins/abnormal_security/icon_abnormal_security/actions/get_case_details/__init__.py
  plugins/abnormal_security/icon_abnormal_security/actions/get_case_details/action.py
  plugins/abnormal_security/icon_abnormal_security/actions/get_case_details/schema.py
  plugins/abnormal_security/icon_abnormal_security/actions/get_cases/__init__.py
  plugins/abnormal_security/icon_abnormal_security/actions/get_cases/action.py
  plugins/abnormal_security/icon_abnormal_security/actions/get_cases/schema.py
  plugins/abnormal_security/icon_abnormal_security/util/api.py
  plugins/abnormal_security/plugin.spec.yaml
  plugins/abnormal_security/requirements.txt
  plugins/abnormal_security/setup.py
  plugins/abnormal_security/unit_test/__init__.py
  plugins/abnormal_security/unit_test/payloads/get_case_details.json.resp
  plugins/abnormal_security/unit_test/payloads/get_case_details2.json.resp
  plugins/abnormal_security/unit_test/payloads/get_cases.json.resp
  plugins/abnormal_security/unit_test/payloads/get_threats.json.resp
  plugins/abnormal_security/unit_test/test_get_case_details.py
  plugins/abnormal_security/unit_test/test_get_cases.py
  plugins/abnormal_security/unit_test/test_get_threats.py
  plugins/abnormal_security/unit_test/util.py
Labels: Ready to Merge
