Repository rapid7/insightconnect-plugins, pull requests merged in 2021-09, with the labels that each got.

#999 Add default PORT in SQL plugin and add unit test
  plugins/sql/.CHECKSUM
  plugins/sql/bin/komand_sql
  plugins/sql/help.md
  plugins/sql/komand_sql/connection/connection.py
  plugins/sql/plugin.spec.yaml
  plugins/sql/setup.py
  plugins/sql/unit_test/__init__.py
  plugins/sql/unit_test/test_connection.py
Labels: Needs 2nd Reviewer

#1001 Add autoupdate Github Action
  .github/workflows/autoupdate.yml
Labels: Autoupdate

#996 [MC-646][MC-697] Improve error messaging in Query Group Membership action in AD LDAP plugin
  plugins/active_directory_ldap/.CHECKSUM
  plugins/active_directory_ldap/bin/komand_active_directory_ldap
  plugins/active_directory_ldap/help.md
  plugins/active_directory_ldap/komand_active_directory_ldap/actions/query_group_membership/action.py
  plugins/active_directory_ldap/plugin.spec.yaml
  plugins/active_directory_ldap/setup.py
  plugins/active_directory_ldap/unit_test/common.py
  plugins/active_directory_ldap/unit_test/test_action_query_group_membership.py
Labels: Needs 2nd Reviewer

#1002 Add monitor incident task to palo alto xdr plugin
  plugins/palo_alto_cortex_xdr/.CHECKSUM
  plugins/palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
  plugins/palo_alto_cortex_xdr/help.md
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/__init__.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_incident_events/__init__.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_incident_events/schema.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_incident_events/task.py
  plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/api.py
  plugins/palo_alto_cortex_xdr/plugin.spec.yaml
  plugins/palo_alto_cortex_xdr/setup.py
Labels: Needs 2nd Reviewer

#995 [MC-669][MC-695][MC-696] Proofpoint Tap - Fix invalid type in custom output in Fetch Forensics action
  plugins/proofpoint_tap/.CHECKSUM
  plugins/proofpoint_tap/bin/komand_proofpoint_tap
  plugins/proofpoint_tap/help.md
  plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/action.py
  plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/schema.py
  plugins/proofpoint_tap/plugin.spec.yaml
  plugins/proofpoint_tap/setup.py
  plugins/proofpoint_tap/unit_test/payloads/all_threats.json.resp
  plugins/proofpoint_tap/unit_test/payloads/all_threats_active_status.json.resp
  plugins/proofpoint_tap/unit_test/payloads/all_threats_cleared_status.json.resp
  plugins/proofpoint_tap/unit_test/payloads/all_threats_without_time_end.json.resp
  plugins/proofpoint_tap/unit_test/payloads/all_threats_without_time_start.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_clicks.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_clicks_cleared_status.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_clicks_without_time_end.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_clicks_without_time_start.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_clicks_without_url.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_messages.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_messages_active_status.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_messages_cleared_status.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_messages_without_subject.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_messages_without_time_end.json.resp
  plugins/proofpoint_tap/unit_test/payloads/blocked_messages_without_time_start.json.resp
  plugins/proofpoint_tap/unit_test/payloads/decode_few_urls.json.resp
  plugins/proofpoint_tap/unit_test/payloads/decode_single_url.json.resp
  plugins/proofpoint_tap/unit_test/payloads/delivered_messages.json.resp
  plugins/proofpoint_tap/unit_test/payloads/delivered_messages_active_status.json.resp
  plugins/proofpoint_tap/unit_test/payloads/delivered_messages_cleared_status.json.resp
  plugins/proofpoint_tap/unit_test/payloads/delivered_messages_without_subject.json.resp
  plugins/proofpoint_tap/unit_test/payloads/delivered_messages_without_time_end.json.resp
  plugins/proofpoint_tap/unit_test/payloads/delivered_messages_without_time_start.json.resp
  plugins/proofpoint_tap/unit_test/payloads/forensics_blacklisted_as_boolean.json.resp
  plugins/proofpoint_tap/unit_test/payloads/forensics_blacklisted_as_boolean_and_integer.json.resp
  plugins/proofpoint_tap/unit_test/payloads/forensics_blacklisted_as_integer.json.resp
  plugins/proofpoint_tap/unit_test/payloads/permitted_clicks.json.resp
  plugins/proofpoint_tap/unit_test/payloads/permitted_clicks_cleared_status.json.resp
  plugins/proofpoint_tap/unit_test/payloads/permitted_clicks_without_time_end.json.resp
  plugins/proofpoint_tap/unit_test/payloads/permitted_clicks_without_time_start.json.resp
  plugins/proofpoint_tap/unit_test/payloads/permitted_clicks_without_url.json.resp
  plugins/proofpoint_tap/unit_test/payloads/top_clickers.json.resp
  plugins/proofpoint_tap/unit_test/payloads/top_clickers_empty_users.json.resp
  plugins/proofpoint_tap/unit_test/test_fetch_forensics.py
  plugins/proofpoint_tap/unit_test/test_get_all_threats.py
  plugins/proofpoint_tap/unit_test/test_get_blocked_clicks.py
  plugins/proofpoint_tap/unit_test/test_get_blocked_messages.py
  plugins/proofpoint_tap/unit_test/test_get_delivered_threats.py
  plugins/proofpoint_tap/unit_test/test_get_permitted_clicks.py
  plugins/proofpoint_tap/unit_test/test_get_top_clickers.py
  plugins/proofpoint_tap/unit_test/test_parse_tap_alert.py
  plugins/proofpoint_tap/unit_test/test_url_decode.py
  plugins/proofpoint_tap/unit_test/test_util.py
Labels: Needs 2nd Reviewer

#989 ServiceNow plugin Get Attachments for an Incident action
  plugins/servicenow/.CHECKSUM
  plugins/servicenow/bin/icon_servicenow
  plugins/servicenow/help.md
  plugins/servicenow/icon_servicenow/actions/__init__.py
  plugins/servicenow/icon_servicenow/actions/get_attachments_for_an_incident/__init__.py
  plugins/servicenow/icon_servicenow/actions/get_attachments_for_an_incident/action.py
  plugins/servicenow/icon_servicenow/actions/get_attachments_for_an_incident/schema.py
  plugins/servicenow/icon_servicenow/actions/get_incident_attachment/action.py
  plugins/servicenow/icon_servicenow/util/request_helper.py
  plugins/servicenow/plugin.spec.yaml
  plugins/servicenow/setup.py
  plugins/servicenow/unit_test/payloads/get_attachment_by_table_sys_id.json.resp
  plugins/servicenow/unit_test/payloads/get_attachment_by_table_sys_id_empty.json.resp
  plugins/servicenow/unit_test/payloads/get_attachment_by_table_sys_id_many.json.resp
  plugins/servicenow/unit_test/payloads/get_attachment_file.resp
  plugins/servicenow/unit_test/test_get_attachments_for_an_incident.py
  plugins/servicenow/unit_test/test_get_incident_attachment.py
  plugins/servicenow/unit_test/util.py
Labels: Ready to Merge

#1013 Update Prospector to Ignore 'inconsistent-return-statements'
  prospector.yaml
Labels: Ready to Merge

#1012 SOAR-6425 Trendmicro Deepsecurity Fix Memory Leak- Request Session
  plugins/trendmicro_deepsecurity/.CHECKSUM
  plugins/trendmicro_deepsecurity/bin/icon_trendmicro_deepsecurity
  plugins/trendmicro_deepsecurity/help.md
  plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/deploy_rules/action.py
  plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/get_rule_details/action.py
  plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/list_rules/action.py
  plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/search_computers/action.py
  plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/search_computers/schema.py
  plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/search_rules/action.py
  plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/connection/connection.py
  plugins/trendmicro_deepsecurity/plugin.spec.yaml
  plugins/trendmicro_deepsecurity/requirements.txt
  plugins/trendmicro_deepsecurity/setup.py
Labels: Needs 2nd Reviewer

#1008 SOAR-6687 Fix Metasploit plugin
  plugins/rapid7_metasploit/.CHECKSUM
  plugins/rapid7_metasploit/Dockerfile
  plugins/rapid7_metasploit/bin/komand_rapid7_metasploit
  plugins/rapid7_metasploit/help.md
  plugins/rapid7_metasploit/komand_rapid7_metasploit/actions/execute_exploit/action.py
  plugins/rapid7_metasploit/komand_rapid7_metasploit/actions/execute_exploit/schema.py
  plugins/rapid7_metasploit/komand_rapid7_metasploit/actions/search_for_exploit/action.py
  plugins/rapid7_metasploit/komand_rapid7_metasploit/actions/search_for_exploit/schema.py
  plugins/rapid7_metasploit/komand_rapid7_metasploit/connection/connection.py
  plugins/rapid7_metasploit/komand_rapid7_metasploit/connection/schema.py
  plugins/rapid7_metasploit/komand_rapid7_metasploit/triggers/new_modules/schema.py
  plugins/rapid7_metasploit/komand_rapid7_metasploit/triggers/new_modules/trigger.py
  plugins/rapid7_metasploit/plugin.spec.yaml
  plugins/rapid7_metasploit/requirements.txt
  plugins/rapid7_metasploit/setup.py
  plugins/rapid7_metasploit/unit_test/test_execute_exploit.py
  plugins/rapid7_metasploit/unit_test/test_new_modules.py
  plugins/rapid7_metasploit/unit_test/test_search_for_exploit.py
Labels: Ready to Merge
