Repository rapid7/insightconnect-plugins, pull requests merged in 2021-05, with the labels that each got.

#886 Add enrichment Plugin to utilize GreyNoise
  greynoise/.CHECKSUM
  greynoise/.dockerignore
  greynoise/.gitignore
  greynoise/Dockerfile
  greynoise/Makefile
  greynoise/bin/icon_greynoise
  greynoise/extension.png
  greynoise/help.md
  greynoise/icon.png
  greynoise/icon_greynoise/__init__.py
  greynoise/icon_greynoise/actions/__init__.py
  greynoise/icon_greynoise/actions/community_lookup/__init__.py
  greynoise/icon_greynoise/actions/community_lookup/action.py
  greynoise/icon_greynoise/actions/community_lookup/schema.py
  greynoise/icon_greynoise/actions/context_lookup/__init__.py
  greynoise/icon_greynoise/actions/context_lookup/action.py
  greynoise/icon_greynoise/actions/context_lookup/schema.py
  greynoise/icon_greynoise/actions/get_tag_details/__init__.py
  greynoise/icon_greynoise/actions/get_tag_details/action.py
  greynoise/icon_greynoise/actions/get_tag_details/schema.py
  greynoise/icon_greynoise/actions/gnql_query/__init__.py
  greynoise/icon_greynoise/actions/gnql_query/action.py
  greynoise/icon_greynoise/actions/gnql_query/schema.py
  greynoise/icon_greynoise/actions/quick_lookup/__init__.py
  greynoise/icon_greynoise/actions/quick_lookup/action.py
  greynoise/icon_greynoise/actions/quick_lookup/schema.py
  greynoise/icon_greynoise/actions/riot_lookup/__init__.py
  greynoise/icon_greynoise/actions/riot_lookup/action.py
  greynoise/icon_greynoise/actions/riot_lookup/schema.py
  greynoise/icon_greynoise/connection/__init__.py
  greynoise/icon_greynoise/connection/connection.py
  greynoise/icon_greynoise/connection/schema.py
  greynoise/icon_greynoise/triggers/__init__.py
  greynoise/icon_greynoise/util/__init__.py
  greynoise/icon_greynoise/util/util.py
  greynoise/plugin.spec.yaml
  greynoise/requirements.txt
  greynoise/setup.py
Labels: Unresolved Comments

#900 MC-438 - CheckPhish - Scan URL - New Plugin/Action
  checkphish/.CHECKSUM
  checkphish/.dockerignore
  checkphish/Dockerfile
  checkphish/Makefile
  checkphish/bin/icon_checkphish
  checkphish/extension.png
  checkphish/help.md
  checkphish/icon.png
  checkphish/icon_checkphish/__init__.py
  checkphish/icon_checkphish/actions/__init__.py
  checkphish/icon_checkphish/actions/scan_url/__init__.py
  checkphish/icon_checkphish/actions/scan_url/action.py
  checkphish/icon_checkphish/actions/scan_url/schema.py
  checkphish/icon_checkphish/connection/__init__.py
  checkphish/icon_checkphish/connection/connection.py
  checkphish/icon_checkphish/connection/schema.py
  checkphish/icon_checkphish/triggers/__init__.py
  checkphish/icon_checkphish/util/__init__.py
  checkphish/icon_checkphish/util/api.py
  checkphish/plugin.spec.yaml
  checkphish/requirements.txt
  checkphish/setup.py
Labels: Needs second reviewer

#891 Add logger in Submit Url for Scan action when domain is on blacklist in Urlscan plugin
  urlscan/.CHECKSUM
  urlscan/bin/komand_urlscan
  urlscan/help.md
  urlscan/komand_urlscan/actions/submit_url_for_scan/action.py
  urlscan/komand_urlscan/actions/submit_url_for_scan/schema.py
  urlscan/plugin.spec.yaml
  urlscan/setup.py
Labels: Needs second reviewer

#901 Cisco Umbrella Investigate python2 to python3 improvements
  cisco_umbrella_investigate/.CHECKSUM
  cisco_umbrella_investigate/bin/komand_cisco_umbrella_investigate
  cisco_umbrella_investigate/help.md
  cisco_umbrella_investigate/komand_cisco_umbrella_investigate/actions/latest_domains/action.py
  cisco_umbrella_investigate/komand_cisco_umbrella_investigate/actions/search/action.py
  cisco_umbrella_investigate/komand_cisco_umbrella_investigate/connection/connection.py
  cisco_umbrella_investigate/komand_cisco_umbrella_investigate/investigate/investigate.py
  cisco_umbrella_investigate/plugin.spec.yaml
  cisco_umbrella_investigate/setup.py
Labels: Needs second reviewer

#912 GreyNoise - Fixes 911 - missing connection parameter
  greynoise/help.md
  greynoise/icon_greynoise/connection/schema.py
  greynoise/plugin.spec.yaml
Labels: Needs second reviewer

#908 InsightIDR convert date to UTC in List Investigations action
  rapid7_insightidr/.CHECKSUM
  rapid7_insightidr/bin/komand_rapid7_insightidr
  rapid7_insightidr/help.md
  rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/action.py
  rapid7_insightidr/plugin.spec.yaml
  rapid7_insightidr/setup.py
Labels: Validation Failure

#914 Rapid7 InsightVM Cloud Plugin Update
  rapid7_insightvm_cloud/.CHECKSUM
  rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
  rapid7_insightvm_cloud/help.md
  rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_scan/action.py
  rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_scan/schema.py
  rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/start_scan/action.py
  rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/start_scan/schema.py
  rapid7_insightvm_cloud/plugin.spec.yaml
  rapid7_insightvm_cloud/setup.py
Labels: Needs 2nd Reviewer

#916 [SOAR-5441][SOAR-5440] - Cortex XDR File Actions
  palo_alto_cortex_xdr/.CHECKSUM
  palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
  palo_alto_cortex_xdr/help.md
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/allow_file/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/allow_file/action.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/allow_file/schema.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/block_file/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/block_file/action.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/block_file/schema.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/api.py
  palo_alto_cortex_xdr/plugin.spec.yaml
  palo_alto_cortex_xdr/unit_test/test_allow_file.py
  palo_alto_cortex_xdr/unit_test/test_block_file.py
Labels: Needs 2nd Reviewer, Validation Failure

#910 [SOAR-5436][SOAR-5439] Cortex XDR
  palo_alto_cortex_xdr/.CHECKSUM
  palo_alto_cortex_xdr/.dockerignore
  palo_alto_cortex_xdr/Dockerfile
  palo_alto_cortex_xdr/Makefile
  palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
  palo_alto_cortex_xdr/extension.png
  palo_alto_cortex_xdr/help.md
  palo_alto_cortex_xdr/icon.png
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/allow_file/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/allow_file/action.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/allow_file/schema.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/block_file/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/block_file/action.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/block_file/schema.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/get_endpoint_details/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/get_endpoint_details/action.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/get_endpoint_details/schema.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/isolate_endpoint/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/isolate_endpoint/action.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/isolate_endpoint/schema.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/connection/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/connection/connection.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/connection/schema.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_incidents/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_incidents/schema.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_incidents/trigger.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/__init__.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/api.py
  palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/util.py
  palo_alto_cortex_xdr/plugin.spec.yaml
  palo_alto_cortex_xdr/requirements.txt
  palo_alto_cortex_xdr/setup.py
  palo_alto_cortex_xdr/unit_test/test_allow_file.py
  palo_alto_cortex_xdr/unit_test/test_api.py
  palo_alto_cortex_xdr/unit_test/test_block_file.py
  palo_alto_cortex_xdr/unit_test/test_connection.py
  palo_alto_cortex_xdr/unit_test/test_get_endpoint_details.py
  palo_alto_cortex_xdr/unit_test/test_get_incidents.py
  palo_alto_cortex_xdr/unit_test/test_isolate_endpoint.py
Labels: Needs 2nd Reviewer

#919 Add in Search Database action `solutions` output field Rapid& VulnDB plugin
  rapid7_vulndb/.CHECKSUM
  rapid7_vulndb/Dockerfile
  rapid7_vulndb/bin/komand_rapid7_vulndb
  rapid7_vulndb/help.md
  rapid7_vulndb/komand_rapid7_vulndb/actions/search_db/action.py
  rapid7_vulndb/komand_rapid7_vulndb/actions/search_db/schema.py
  rapid7_vulndb/plugin.spec.yaml
  rapid7_vulndb/setup.py
Labels: Needs 2nd Reviewer

#923 Cloud IVM Plugin Update Start Scan Output
  rapid7_insightvm_cloud/.CHECKSUM
  rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
  rapid7_insightvm_cloud/help.md
  rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/start_scan/action.py
  rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/start_scan/schema.py
  rapid7_insightvm_cloud/plugin.spec.yaml
  rapid7_insightvm_cloud/setup.py
Labels: Needs 2nd Reviewer
