Repository rapid7/insightconnect-plugins, pull requests merged in 2021-04, with the labels that each got.

#865 Update Search action in Zendesk plugin
  zendesk/.CHECKSUM
  zendesk/bin/komand_zendesk
  zendesk/help.md
  zendesk/komand_zendesk/actions/delete_membership/schema.py
  zendesk/komand_zendesk/actions/delete_user/schema.py
  zendesk/komand_zendesk/actions/search/action.py
  zendesk/komand_zendesk/actions/search/schema.py
  zendesk/komand_zendesk/actions/show_memberships/schema.py
  zendesk/komand_zendesk/actions/show_user/schema.py
  zendesk/komand_zendesk/actions/suspend_user/schema.py
  zendesk/komand_zendesk/actions/update_ticket/schema.py
  zendesk/plugin.spec.yaml
  zendesk/setup.py
Labels: Needs second reviewer

#846 [MC-55] Added support for IPV6 in all actions.
  fortinet_fortigate/.CHECKSUM
  fortinet_fortigate/bin/icon_fortinet_fortigate
  fortinet_fortigate/help.md
  fortinet_fortigate/icon_fortinet_fortigate/actions/add_address_object_to_address_group/action.py
  fortinet_fortigate/icon_fortinet_fortigate/actions/check_if_address_in_group/action.py
  fortinet_fortigate/icon_fortinet_fortigate/actions/create_address_object/action.py
  fortinet_fortigate/icon_fortinet_fortigate/actions/delete_address_object/action.py
  fortinet_fortigate/icon_fortinet_fortigate/actions/remove_address_object_from_group/action.py
  fortinet_fortigate/icon_fortinet_fortigate/connection/connection.py
  fortinet_fortigate/plugin.spec.yaml
  fortinet_fortigate/setup.py
Labels: Unresolved Comments

#866 Cisco thread grid change type in input private from string to boolean
  cisco_threatgrid/.CHECKSUM
  cisco_threatgrid/bin/icon_cisco_threatgrid
  cisco_threatgrid/help.md
  cisco_threatgrid/icon_cisco_threatgrid/actions/submit_sample/action.py
  cisco_threatgrid/icon_cisco_threatgrid/actions/submit_sample/schema.py
  cisco_threatgrid/plugin.spec.yaml
  cisco_threatgrid/setup.py
Labels: Unresolved Comments

#871 Netmiko plugin improvements
  netmiko/.CHECKSUM
  netmiko/Dockerfile
  netmiko/bin/komand_netmiko
  netmiko/help.md
  netmiko/komand_netmiko/actions/configuration_commands/action.py
  netmiko/komand_netmiko/actions/configuration_commands/schema.py
  netmiko/komand_netmiko/actions/show_commands/action.py
  netmiko/komand_netmiko/actions/show_commands/schema.py
  netmiko/komand_netmiko/connection/connection.py
  netmiko/komand_netmiko/connection/schema.py
  netmiko/plugin.spec.yaml
  netmiko/requirements.txt
  netmiko/setup.py
Labels: Ready to Schipp

#883 New plugin - EasyVista
  easyvista/.CHECKSUM
  easyvista/.dockerignore
  easyvista/Dockerfile
  easyvista/Makefile
  easyvista/bin/icon_easyvista
  easyvista/extension.png
  easyvista/help.md
  easyvista/icon.png
  easyvista/icon_easyvista/__init__.py
  easyvista/icon_easyvista/actions/__init__.py
  easyvista/icon_easyvista/actions/close_ticket/__init__.py
  easyvista/icon_easyvista/actions/close_ticket/action.py
  easyvista/icon_easyvista/actions/close_ticket/schema.py
  easyvista/icon_easyvista/actions/create_ticket/__init__.py
  easyvista/icon_easyvista/actions/create_ticket/action.py
  easyvista/icon_easyvista/actions/create_ticket/schema.py
  easyvista/icon_easyvista/actions/search_tickets/__init__.py
  easyvista/icon_easyvista/actions/search_tickets/action.py
  easyvista/icon_easyvista/actions/search_tickets/schema.py
  easyvista/icon_easyvista/actions/update_ticket/__init__.py
  easyvista/icon_easyvista/actions/update_ticket/action.py
  easyvista/icon_easyvista/actions/update_ticket/schema.py
  easyvista/icon_easyvista/connection/__init__.py
  easyvista/icon_easyvista/connection/connection.py
  easyvista/icon_easyvista/connection/schema.py
  easyvista/icon_easyvista/triggers/__init__.py
  easyvista/icon_easyvista/util/__init__.py
  easyvista/icon_easyvista/util/api.py
  easyvista/plugin.spec.yaml
  easyvista/requirements.txt
  easyvista/setup.py
Labels: Needs Icon
